name: resas
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/myConsciousness/resas

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  cache_storage: ^1.0.0
  collection: ^1.15.0
  http: ^0.13.4
  json_pro: ^1.0.0
  sweet_cookie_jar: ^1.0.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  import_sorter: ^4.6.0
