name: resas
description: A most easily usable RESAS API wrapper in Dart. With this library, you can easily integrate your application with the RESAS API.
version: 0.2.0
homepage: https://github.com/myConsciousness/resas

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  cache_storage: ^1.0.0
  collection: ^1.15.0
  freezed_annotation: ^1.1.0
  http: ^0.13.4
  json_response: ^2.3.2
  json_serializable: ^6.1.3


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  import_sorter: ^4.6.0
  build_runner: ^2.1.7
  freezed: ^1.1.1
